### ISSUE TITLE
incorrrect BNS function in code

### ISSUE THREAD

**Issue by gforman44** [Kensuke-Mitsuzawa/DocumentFeatureSelection#27]
This code is incorrect for BNS.   abs(norm.ppf(tpr) - norm.ppf(fpr))
And you must filter away words that occur < 3 times (tp+fp counts).
If you only want positively associated words, drop the abs().

https://github.com/Kensuke-Mitsuzawa/DocumentFeatureSelection/blob/b038d261beaeca9d662fa71096295468e55992dd/DocumentFeatureSelection/bns/bns_python3.py#L65

**Comment by Kensuke-Mitsuzawa** [comment]
Thank you for your comment.
As your suggestion, I made a mistake in using `norm.ppf` , I should correct it.

for `And you must filter away words that occur < 3 times (tp+fp counts).` , could you show me a reference for that?
