### ISSUE TITLE
BNS Clarification needed: DocFreq or TermFreq?

### ISSUE THREAD

**Issue by nkrot** [Kensuke-Mitsuzawa/DocumentFeatureSelection#35]
I have been looking through the examples in the repo of how BNS is computed and came across the following. As can be seen from the naming of the methods, in the 1st case it is **Term Frequency** meanwhile in the 2nd case it is **Document Frequency**. Could you please clarify which is correct?

1) in `examples/basic_example.py` that uses `DocumentFeatureSelection/interface.py`, line 128:

    matrix_data_object = data_converter.DataConverter().convert_multi_docs2term_frequency_matrix(...)

2) in `tests/test_bns_python3.py` line 105:

    data_csr_matrix = data_converter.DataConverter().labeledMultiDocs2DocFreqMatrix(...)

Thank you in advance,

**Comment by Kensuke-Mitsuzawa** [comment]
@nkrot Thanks for your suggestion. DocFreq is correct. Thus, a code in interface.py is incorrect. I should make it correction.

For your informatio, the original paper `George Forman, "An Extensive Empirical Study of Feature Selection Metrics for Text Classification",Journal of Machine Learning Research 3 (2003) 1289-1305` says 

<img width="627" alt="2018-10-24 10 27 42" src="https://user-images.githubusercontent.com/1772712/47400313-9c68e400-d777-11e8-8455-1a287208de92.png">

And the notation is
<img width="557" alt="2018-10-24 10 30 58" src="https://user-images.githubusercontent.com/1772712/47400401-eeaa0500-d777-11e8-9191-9ee28421f955.png">

Here, `case` means #Doc , therefore this should be document frequency.
